permalink: csspace
title: 'CS Group - SPACE Business Unit'
collections_dir: collections
destination: ../3-deliveries/webref_html
description: Official page for the Space Business Unit of CS Group
url: https://uk.c-s.fr/
author: CS Group
logo: images/logo-cs.png
lang : en_UK
encoding: utf-8

collections:
  products:
    output: true
    permalink: /:name.html
  features:
    output: true
    permalink: /:name.html
  references:
    output: true
    permalink: /:name.html

  
defaults:
  - scope:
        type: products
    values:
        layout: product
  - scope:
        path: 'images'
    values:
        image: true
  - scope:
        type: references
    values:
        layout: reference
  - scope:
        type: features
    values:
        layout: feature
      
sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag